spring.application.name=BibSoft
spring.datasource.url=jdbc:postgresql://localhost:5432/bibsoft
spring.datasource.username=postgres
spring.datasource.password=aragon36
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect